version: '3'

volumes:
  pgdata:

services:
  postgres:
    image: postgis/postgis:14-master
    ports:
      - 5432:5432
    restart: unless-stopped
    security_opt:
      - no-new-privileges=true
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_DB_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    command: [ "postgres",
                   "-c", "log_statement=all",
                   "-c", "logging_collector=true",
                   "-c", "log_rotation_size=250000",
                   "-c", "log_file_mode=0644",
                   "-c", "log_directory=/var/log/postgresql",
                   "-c", "log_filename=postgresql.log",
                   "-c", "max_connections=200" ]
    volumes:
      - pgdata:/var/lib/postgresql/data
      - /data/postgres/logs:/var/log/postgresql
      #- ./postgresql/audit.sql:/docker-entrypoint-initdb.d/1-audit.sql
    logging:
          driver: "json-file"
    networks:
      - esnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_DB_USERNAME} -d ${POSTGRES_DB_NAME}"]
      interval: 1m
      timeout: 10s
      retries: 3

networks:
  esnet:
    driver: bridge
