version: '3.9'

volumes:
   geoserver-data:

services:
  geoserver:
      image: docker.osgeo.org/geoserver:2.23.x
      container_name: geoserver
      ports:
        - "8083:8080"
      restart: on-failure
      environment:
      - INSTALL_EXTENSIONS=true
      - STABLE_EXTENSIONS=wps,csw
      - EXTRA_JAVA_OPTS=-Xms1G -Xmx2G
      volumes:
      - ./geoserver_data:/opt/geoserver_data/:Z
      - ./additional_libs:/opt/additional_libs:Z
      restart: unless-stopped
      networks:
      - esnet
      healthcheck:
        test: curl --fail -s http://localhost:8083/ || exit 1
        interval: 1m30s
        timeout: 10s
        retries: 3

  nginx:
      # override to add nginx config for geoserver
      volumes:
            # default
            - ./geoserver/nginx/locations/geoserver.inc:/etc/nginx/locations/geoserver.inc
networks:
  esnet:
    driver: bridge
