version: '3.1'

volumes:
  geonetwork4:
  esdata9:
  pgdata:
  pglog:
  nginxlog:
  apachelog:


networks:
  gn-network:
    driver: bridge


services:
  www:
    image: nginx
    ports:
      - 81:80
    environment:
      # Only used for / redirect to default webapp
      - NGINX_PUBLIC_HOST=localhost
      #- NGINX_PUBLIC_HOST=apps.titellus.net
      - NGINX_HOST=0.0.0.0
      - NGINX_PORT=80
    volumes:
      - ./nginx:/etc/nginx/templates
      - nginxlog:/var/log/nginx
    # depends_on:
    #   - geonetwork
    networks:
      - gn-network

#  www:
#    image: httpd
#    ports:
#      - 81:80
#    volumes:
#      - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
#      - ./apache/gn-httpd.conf:/usr/local/apache2/conf/gn-httpd.conf
#      - apachelog:/usr/local/apache2/logs
#    depends_on:
#      - geonetwork
#    networks:
#      - gn-network


  database:
    image: mdillon/postgis
    environment:
      POSTGRES_USER: geonetwork
      POSTGRES_PASSWORD: geonetwork
      POSTGRES_DB: geonetwork
    command: [ "postgres",
               "-c", "log_statement=all",
               "-c", "logging_collector=true",
               "-c", "log_file_mode=0644",
               "-c", "log_directory=/var/log/postgresql",
               "-c", "log_filename=postgresql.log" ]
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pglog:/var/log/postgresql
    networks:
      - gn-network


  # geonetwork:
  #   image: geonetwork:4.0.2
  #   restart: always
  #   ports:
  #     - 8080:8080
  #   environment:
  #     DATA_DIR: /catalogue-data

  #     JAVA_OPTS:
  #       -Dorg.eclipse.jetty.annotations.AnnotationParser.LEVEL=OFF
  #       -Djava.security.egd=file:/dev/./urandom -Djava.awt.headless=true
  #       -Xms512M -Xss512M -Xmx2G -XX:+UseConcMarkSweepGC
  #       -Dgeonetwork.resources.dir=/catalogue-data/resources
  #       -Dgeonetwork.data.dir=/catalogue-data
  #       -Dgeonetwork.codeList.dir=/var/lib/jetty/webapps/geonetwork/WEB-INF/data/config/codelist
  #       -Dgeonetwork.schema.dir=/var/lib/jetty/webapps/geonetwork/WEB-INF/data/config/schema_plugins

  #     ES_HOST: elasticsearch
  #     ES_PROTOCOL: http
  #     ES_PORT: 9200

  #     KB_URL: http://kibana:5601

  #     GEONETWORK_DB_TYPE: postgres
  #     GEONETWORK_DB_HOST: database
  #     GEONETWORK_DB_PORT: 5432
  #     GEONETWORK_DB_NAME: geonetwork
  #     GEONETWORK_DB_USERNAME: geonetwork
  #     GEONETWORK_DB_PASSWORD: geonetwork
  #   volumes:
  #     - geonetwork4:/catalogue-data
  #     - /home/jo/Git/iso19139.gemini23/src/main/plugin/iso19139.gemini23:/var/lib/jetty/webapps/geonetwork/WEB-INF/data/config/schema_plugins/iso19139.gemini23
  #     - /home/jo/Git/iso19139.nonspatial/src/main/plugin/iso19139.nonspatial:/var/lib/jetty/webapps/geonetwork/WEB-INF/data/config/schema_plugins/iso19139.nonspatial
  #     - /home/jo/Git/dcat2/src/main/plugin/dcat2:/var/lib/jetty/webapps/geonetwork/WEB-INF/data/config/schema_plugins/dcat2
  #     - /home/jo/Git/iso19139.gemini23/target/schema-iso19139.gemini23-3.7.jar:/var/lib/jetty/webapps/geonetwork/WEB-INF/lib/schema-iso19139.gemini23-3.7.jar
  #     - /home/jo/Git/iso19139.nonspatial/target/schema-iso19139.nonspatial-3.7.jar:/var/lib/jetty/webapps/geonetwork/WEB-INF/lib/schema-iso19139.nonspatial-3.7.jar

  #   depends_on:
  #     - elasticsearch
  #     - database
  #   networks:
  #     - gn-network


  # elasticsearch:
  #   image: elasticsearch:7.9.2
  #   ports:
  #     - 9200:9200
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #     nofile:
  #       soft: 65536
  #       hard: 65536
  #   environment:
  #     ES_JAVA_OPTS: "-Xms1G -Xmx1G"
  #     discovery.type: single-node
  #   volumes:
  #     - esdata9:/usr/share/elasticsearch/data
  #   networks:
  #     - gn-network

  # kibana:
  #   image: kibana:7.9.2
  #   environment:
  #     SERVER_NAME: 'kibana'
  #     ELASTICSEARCH_URL: http://elasticsearch:9200/
  #     SERVER_BASEPATH: /geonetwork/dashboards
  #     SERVER_REWRITEBASEPATH: 'false'
  #     KIBANA_INDEX: .dashboards
  #     XPACK_MONITORING_UI_CONTAINER_ELASTICSEARCH_ENABLED: 'true'
  #   networks:
  #     - gn-network