version: '3'

volumes:
  zpdata:

services:
  zeppelin:
    image: apache/zeppelin:0.9.0
    container_name: zeppelin
    volumes: 
      - zpdata:/zeppelin
      - ./shiro-geonetwork/geonetwork-integration/target/testshiro-1.0-SNAPSHOT-jar-with-dependencies.jar:/opt/zeppelin/lib/testshiro-1.0-SNAPSHOT-jar-with-dependencies.jar
      - ./zeppelin/zeppelin-notebook:/zeppelin/notebook
      - ./zeppelin/zeppelin-logs:/zeppelin/logs
      - ./shiro-geonetwork/lib/postgresql-42.2.12.jar:/opt/zeppelin/lib/postgresql-42.2.12.jar
      - ./shiro-geonetwork/conf/shiro.ini:/opt/zeppelin/conf/shiro.ini
      - ./zeppelin/zeppelin-conf/interpreter-setting.json:/zeppelin/interpreter/jdbc/interpreter-setting.json
    environment:
      - "ZEPPELIN_INTERPRETER_OUTPUT_LIMIT=10490000"
      - "ZEPPELIN_INTERPRETER_INCLUDE=jdbc"  
      - "ZEPPELIN_INTERPRETER_GROUP_DEFAULT=jdbc"
      - "ZEPPELIN_INTERPRETER_DIR=/zeppelin/interpreter"
      - "ZEPPELIN_NOTEBOOK_DIR=/zeppelin/notebook"
      - "ZEPPELIN_PORT=8081"
      - "ZEPPELIN_ADDR=0.0.0.0"
      - "HOSTNAME=0.0.0.0"
    ports:
      - "8081:8081"
    security_opt:
      - no-new-privileges=true
    networks:
      - esnet
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8081/health/readiness || exit 1"]
      interval: 3m
      timeout: 10s
      retries: 5
    restart: unless-stopped

networks:
  esnet:
    driver: bridge