version: '2.2'

# run me with:
#  either (non-headless, linux only) xhost + && docker-compose -f docker-compose-dev.yml run --rm  -e "DISPLAY=$DISPLAY" integration mvn clean test -Dbrowser=firefox -DendPointToTest=http://yourgeonetworkurl/geonetwork
#  or docker-compose -f docker-compose-dev.yml run --rm  -e "MOZ_HEADLESS=1" integration mvn clean test -Dbrowser=firefox -DendPointToTest=http://yourgeonetworkurl/geonetwork



services:

  integration:
    container_name: integration
    build:
      context: .
      dockerfile: ./testing/Dockerfile
    volumes:
      - ./testing:/testing
    working_dir: /testing
    network_mode: "host"
    environment:
      - DISPLAY