version: '3'

volumes:
  esdata:
  geonetwork:
  pglog:
  nginxlog:
  apachelog:

services:
  geonetwork:
    image: geonetwork:latest
    restart: always
    ports:
      - 8080:8080
    user: 0:0
    environment:
      DATA_DIR: /catalogue-data

      JAVA_OPTS: 
        -Dorg.eclipse.jetty.annotations.AnnotationParser.LEVEL=OFF
        -Djava.security.egd=file:/dev/./urandom -Djava.awt.headless=true
        -Xms512M -Xss512M -Xmx2G -XX:+UseConcMarkSweepGC
        -Dgeonetwork.resources.dir=/catalogue-data/resources
        -Dgeonetwork.data.dir=/catalogue-data
        -Dgeonetwork.codeList.dir=/var/lib/jetty/webapps/geonetwork/WEB-INF/data/config/codelist
        -Dgeonetwork.schema.dir=/var/lib/jetty/webapps/geonetwork/WEB-INF/data/config/schema_plugins
      ES_HOST: elasticsearch
      ES_PROTOCOL: http
      ES_PORT: 9200

      KB_URL: http://kibana:5601

      GEONETWORK_DB_TYPE: postgres
      GEONETWORK_DB_HOST: ${POSTGRES_DB_HOST}
      GEONETWORK_DB_PORT: ${POSTGRES_DB_PORT}
      GEONETWORK_DB_NAME: ${POSTGRES_DB_NAME}
      GEONETWORK_DB_USERNAME: ${POSTGRES_DB_USERNAME}
      GEONETWORK_DB_PASSWORD: ${POSTGRES_DB_PASSWORD}
      GEONETWORK_MICROSERVICESPROXY_TARGETURI: http://ogc-api-records-service:8080
    volumes:
      - geonetwork:/catalogue-data
      - ../iso19139.gemini23/src/main/plugin/iso19139.gemini23:/var/lib/jetty/webapps/geonetwork/WEB-INF/data/config/schema_plugins/iso19139.gemini23
      - ../iso19139.gemini23/src/main/config/translations/en-schema-iso19139.gemini23.json:/var/lib/jetty/webapps/geonetwork/catalog/locales/en-schema-iso19139.gemini23.json
      - ../iso19139.gemini23/target/schema-iso19139.gemini23-4.2.2-SNAPSHOT.jar:/var/lib/jetty/webapps/geonetwork/WEB-INF/lib/schema-iso19139.gemini23-4.2.2-SNAPSHOT.jar
      - ../iso19139.gemini22/src/main/plugin/iso19139.gemini22:/var/lib/jetty/webapps/geonetwork/WEB-INF/data/config/schema_plugins/iso19139.gemini22
      - ../iso19139.gemini22/src/main/config/translations/en-schema-iso19139.gemini22.json:/var/lib/jetty/webapps/geonetwork/catalog/locales/en-schema-iso19139.gemini22.json
      - ../iso19139.gemini22/target/schema-iso19139.gemini22-4.2.2-SNAPSHOT.jar:/var/lib/jetty/webapps/geonetwork/WEB-INF/lib/schema-iso19139.gemini22-4.2.2-SNAPSHOT.jar
      #- ../iso19139.eamp/src/main/plugin/iso19139.eamp:/var/lib/jetty/webapps/geonetwork/WEB-INF/data/config/schema_plugins/iso19139.eamp
      #- ../iso19139.eamp/target/gn-schema-iso19139.eamp-4.2.0-0.jar:/var/lib/jetty/webapps/geonetwork/WEB-INF/lib/gn-schema-iso19139.eamp-4.2.0-0.jar
      # - ../iso19139.nonspatial/src/main/plugin/iso19139.nonspatial:/var/lib/jetty/webapps/geonetwork/WEB-INF/data/config/schema_plugins/iso19139.nonspatial
      # - ../iso19139.nonspatial/target/gn-schema-iso19139.nonspatial-4.2.0-0.jar:/var/lib/jetty/webapps/geonetwork/WEB-INF/lib/gn-schema-iso19139.nonspatial-4.2.0-0.jar
    # depends_on:
    #   - elasticsearch
    #   - database
    networks:
      - esnet

  datahub:
    image: geonetwork/geonetwork-ui-datahub:master
    container_name: datahub
    ports:
      - 8081:80
    environment:
      GN4_API_URL: http://${DH_HOST}:{DH_PORT}/geonetwork/srv/api
    restart: always
    networks:
    - esnet

  ogc-api-records-service:
    image: geonetwork/gn-cloud-ogc-api-records-service:0.2.0
    environment:
      SPRING_PROFILES_ACTIVE: standalone
      SPRING_DATASOURCE_URL: jdbc:postgresql://${POSTGRES_DB_HOST}:${POSTGRES_DB_PORT}/${POSTGRES_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_DB_PASSWORD}
      GN_BASEURL: http://${GN_HOST}:${GN_PORT}/geonetwork/api
      GN_LEGACY_URL: http://${GN_HOST}:${GN_PORT}/geonetwork
      GN_INDEX_URL: ${ES_URL}
      SERVER_FORWARDHEADERSSTRATEGY: FRAMEWORK

    # depends_on:
    #   - database
    #   - elasticsearch
    networks:
      - esnet


  

  nginx:
    image: nginx
    container_name: nginx
    volumes:
          - ./nginx/default.local:/etc/nginx/conf.d/default.conf
          - ./nginx/servers:/etc/ngifnx/servers
          - ./nginx/locations:/etc/nginx/locations
          - ./nginx/root/robots.txt:/var/www/html/robots.txt
          - nginxlog:/var/log/nginx
          # - ./certs/letsencrypt/live:/etc/nginx/certs
          # - ./certs/dhparam.pem:/etc/nginx/ssl/dhparam.pem
    ports:
      - "80:80"
      # - "82:82"
      # - "8443:8443"
    security_opt:
      - no-new-privileges=true
    logging:
          driver: "json-file"
    networks:
      - esnet
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/robots.txt || exit 1"]
      interval: 1m
      timeout: 10s
      retries: 5
    restart: unless-stopped

networks:
  esnet:
    driver: bridge