version: '3'

services:
  geonetwork:
    volumes:
      # client-specific customisations
      # nrw profile
      - ../iso19139.nrw/src/main/plugin/iso19139.nrw:/var/lib/jetty/webapps/geonetwork/WEB-INF/data/config/schema_plugins/iso19139.nrw
      #- ../iso19139.nrw/src/main/config/translations/en-schema-iso19139.nrw.json:/var/lib/jetty/webapps/geonetwork/catalog/locales/en-schema-iso19139.nrw.json
      - ../iso19139.nrw/target/gn-schema-iso19139.nrw-4.2.8-SNAPSHOT.jar:/var/lib/jetty/webapps/geonetwork/WEB-INF/lib/gn-schema-iso19139.nrw-4.2.8-SNAPSHOT.jar
      # post-processing scripts
      - ./nrw/sub-portal-postprocessing/gmd-gemini-postprocessing.xsl:/var/lib/jetty/webapps/geonetwork/xsl/conversion/export/gmd-gemini-postprocessing.xsl
      - ./nrw/sub-portal-postprocessing/gmd-medin-postprocessing.xsl:/var/lib/jetty/webapps/geonetwork/xsl/conversion/export/gmd-medin-postprocessing.xsl
      # Google Analytics code
      - ./nrw/xslt/base-layout.xsl:/var/lib/jetty/webapps/geonetwork/xslt/base-layout.xsl
      - ./nrw/xslt/render-html.xsl:/var/lib/jetty/webapps/geonetwork/xslt/common/render-html.xsl
      # add Welsh to the language selector
      - ./nrw/geonetwork/catalog/js/CatController.js:/var/lib/jetty/webapps/geonetwork/catalog/js/CatController.js
      # Welsh translation files
      - ./nrw/geonetwork/catalog/locales/cym-admin.json:/var/lib/jetty/webapps/geonetwork/catalog/locales/cym-admin.json
      - ./nrw/geonetwork/catalog/locales/cym-core.json:/var/lib/jetty/webapps/geonetwork/catalog/locales/cym-core.json
      - ./nrw/geonetwork/catalog/locales/cym-custom.json:/var/lib/jetty/webapps/geonetwork/catalog/locales/cym-custom.json
      - ./nrw/geonetwork/catalog/locales/cym-editor.json:/var/lib/jetty/webapps/geonetwork/catalog/locales/cym-editor.json
      - ./nrw/geonetwork/catalog/locales/cym-search.json:/var/lib/jetty/webapps/geonetwork/catalog/locales/cym-search.json
      # sub-portals
      - ./nrw/sub-portal-postprocessing/gmd-gemini-postprocessing.xsl:/var/lib/jetty/webapps/geonetwork/WEB-INF/data/config/schema_plugins/iso19139.nrw/present/csw/gmd-gemini-postprocessing.xsl
      - ./nrw/sub-portal-postprocessing/gmd-medin-postprocessing.xsl:/var/lib/jetty/webapps/geonetwork/WEB-INF/data/config/schema_plugins/iso19139.nrw/present/csw/gmd-medin-postprocessing.xsl
      # custom branding
      - ./nrw/geonetwork/catalog/style/srv_custom_style.less:/var/lib/jetty/webapps/geonetwork/catalog/style/srv_custom_style.less
      - ./nrw/geonetwork/catalog/style/GothamRnd-Medium.otf:/var/lib/jetty/webapps/geonetwork/catalog/style/GothamRnd-Medium.otf
      - ./nrw/geonetwork/catalog/style/GothamRnd-MedIta.otf:/var/lib/jetty/webapps/geonetwork/catalog/style/GothamRnd-MediumIta.otf
      - ./nrw/geonetwork/catalog/style/GothamRnd-Bold.otf:/var/lib/jetty/webapps/geonetwork/catalog/style/GothamRnd-Bold.otf
      - ./nrw/geonetwork/catalog/style/GothamRnd-BoldIta.otf:/var/lib/jetty/webapps/geonetwork/catalog/style/GothamRnd-BoldIta.otf
      - ./nrw/geonetwork/catalog/style/GothamRnd-Book.otf:/var/lib/jetty/webapps/geonetwork/catalog/style/GothamRnd-Book.otf
      - ./nrw/geonetwork/catalog/style/GothamRnd-BookIta.otf:/var/lib/jetty/webapps/geonetwork/catalog/style/GothamRnd-BookIta.otf
      - ./nrw/geonetwork/catalog/style/GothamRnd-Light.otf:/var/lib/jetty/webapps/geonetwork/catalog/style/GothamRnd-Light.otf
      - ./nrw/geonetwork/catalog/style/GothamRnd-LightIta.otf:/var/lib/jetty/webapps/geonetwork/catalog/style/GothamRnd-LightIta.otf
      # remove extraneous advanced search options
      - ./nrw/geonetwork/catalog/components/search/searchoptions.html:/var/lib/jetty/webapps/geonetwork/catalog/components/search/searchoptions/partials/searchoptions.html
      - ./nrw/geonetwork/catalog/views/default/templates/advancedSearchForm/defaultAdvancedSearchForm.html:/var/lib/jetty/webapps/geonetwork/catalog/views/default/templates/advancedSearchForm/defaultAdvancedSearchForm.html
      # hide search minimap
      - ./nrw/geonetwork/xslt/base-layout-cssjs-loader.xsl:/var/lib/jetty/webapps/geonetwork/xslt/base-layout-cssjs-loader.xsl

  ogc-api-records-service:
    volumes:
      - ./nrw/ogc-api/copy/copy-iso19139.nrw.xsl:/workspace/BOOT-INF/classes/xslt/ogcapir/formats/copy/copy-iso19139.nrw.xsl

  nginx:
    volumes:
      - ./nrw/nginx/servers/cyfoethnaturiol_cymru.inc:/etc/nginx/servers/cyfoethnaturiol_cymru.inc