version: '2'

#x-aws-vpc: vpc-0d6398060b3738286

volumes:
  geonetwork:
  esdata:
  pgdata:

services:
  geonetwork:
    image: geonetwork:3.10.5

    #restart: always
    ports:
      - 8080:8080
      - 443:443
    environment:
      DATA_DIR: /catalogue-data

      JAVA_OPTS: 
        -Dorg.eclipse.jetty.annotations.AnnotationParser.LEVEL=OFF
        -Djava.security.egd=file:/dev/./urandom -Djava.awt.headless=true
        -Xms512M -Xss512M -Xmx2G -XX:+UseConcMarkSweepGC
        -Dgeonetwork.resources.dir=/catalogue-data/resources
        -Dgeonetwork.data.dir=/catalogue-data
        -Dgeonetwork.codeList.dir=/var/lib/jetty/webapps/geonetwork/WEB-INF/data/config/codelist
        -Dgeonetwork.schema.dir=/var/lib/jetty/webapps/geonetwork/WEB-INF/data/config/schema_plugins

      ES_HOST: localhost
      ES_PROTOCOL: http
      ES_PORT: 9200

      KB_URL: http://localhost:5601

      GEONETWORK_DB_TYPE: postgres
      GEONETWORK_DB_HOST: localhost
      GEONETWORK_DB_PORT: 5432
      GEONETWORK_DB_NAME: geonetwork
      GEONETWORK_DB_USERNAME: geonetwork
      GEONETWORK_DB_USERNAME: geonetwork
      # POSTGRES_DB_PASSWORD: geonetwork
      # POSTGRES_DB_USERNAME: geonetwork
    volumes:
      - geonetwork:/catalogue-data
      - /home/ec2-user/schemas/iso19139.gemini23-3.10.x/src/main/plugin/iso19139.gemini23:/var/lib/jetty/webapps/geonetwork/WEB-INF/data/config/schema_plugins/iso19139.gemini23
      - /home/ec2-user/schemas/iso19139.gemini23-3.10.x/schema-iso19139.gemini23-3.7.jar:/var/lib/jetty/webapps/geonetwork/WEB-INF/lib/schema-iso19139.gemini23-3.7.jar
    # logging:
    #       driver: awslogs
    #       options: 
    #         awslogs-group: docker-geonetwork
    #         awslogs-region: eu-west-2
    #         awslogs-stream-prefix: geonetwork

  elasticsearch:
    image: elasticsearch:7.6.2
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    environment:
      ES_JAVA_OPTS: "-Xms1G -Xmx1G"
      discovery.type: single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data
  #   logging:
  #         driver: awslogs
  #         options: 
  #           awslogs-group: docker-geonetwork
  #           awslogs-region: eu-west-2
  #           awslogs-stream-prefix: geonetwork

  kibana:
    image: kibana:7.6.2
    environment:
      SERVER_NAME: 'kibana'
      ELASTICSEARCH_URL: http://elasticsearch:9200/
      SERVER_BASEPATH: /geonetwork/dashboards
      SERVER_REWRITEBASEPATH: 'false'
      KIBANA_INDEX: .dashboards
      XPACK_MONITORING_UI_CONTAINER_ELASTICSEARCH_ENABLED: 'true'
  #   logging:
  #         driver: awslogs
  #         options: 
  #           awslogs-group: docker-geonetwork
  #           awslogs-region: eu-west-2
  #           awslogs-stream-prefix: geonetwork

  postgres:
    image: postgis/postgis:12-master
    environment:
      POSTGRES_USER: geonetwork
      POSTGRES_PASSWORD: geonetwork
      POSTGRES_DB: geonetwork
    volumes:
      - pgdata:/var/lib/postgresql/data
    # ports:
    #   - 5432:5432
    # logging:
    #       driver: awslogs
    #       options: 
    #         awslogs-group: docker-geonetwork
    #         awslogs-region: eu-west-2
    #         awslogs-stream-prefix: geonetwork


