version: '3'

volumes:
  gndata:
  esdata:
  pgdata:

services:
  geonetwork:
    #image: public.ecr.aws/d7m3b2m9/ea-custom-geonetwork:latest
    #image: geonetwork:4.0.2
    #image: geonetwork:3.12
    image: ea-geonetwork:v0
    # build:
    #   context: .
    #   dockerfile: Dockerfile.local
    container_name: geonetwork
    ports:
      - 8080:8080
    environment:
      DATA_DIR: /catalogue-data
      KB_URL: http://kibana:5601
      GEONETWORK_DB_TYPE: postgres
      GEONETWORK_DB_HOST: ${GEONETWORK_DB_HOST}
      GEONETWORK_DB_PORT: 5432
      GEONETWORK_DB_NAME: ${POSTGRES_DB_NAME}
      GEONETWORK_DB_USERNAME: ${POSTGRES_DB_USERNAME}
      GEONETWORK_DB_PASSWORD: ${POSTGRES_DB_PASSWORD}
      JAVA_OPTS: 
        -Dorg.eclipse.jetty.annotations.AnnotationParser.LEVEL=OFF
        -Djava.security.egd=file:/dev/./urandom -Djava.awt.headless=true
        -Xms512M -Xss512M -Xmx2G -XX:+UseConcMarkSweepGC
        -Dgeonetwork.resources.dir=/catalogue-data/resources
        -Dgeonetwork.data.dir=/catalogue-data
        -Dgeonetwork.codeList.dir=/catalogue-data/thesauri
        -Dgeonetwork.schema.dir=/usr/local/tomcat/webapps/geonetwork/WEB-INF/data/config/schema_plugins
        -Dkb.url=http://kibana:5601
    logging:
      driver: "json-file"
    healthcheck:
      test: ["CMD-SHELL", "curl -i -H \"Accept: application/json\" -f http://localhost:8080/geonetwork/srv/api/0.1/site || exit 1"]
      interval: 1m
      timeout: 10s
      retries: 5
    networks:
      - esnet
    volumes:
      # general overrides
      - gndata:/catalogue-data
      - ./thesauri:/catalogue-data/thesauri
      # skins
      - ../geonetwork-ea-skin/templates/footer.html:/usr/local/tomcat/webapps/geonetwork/catalog/views/default/templates/footer.html
      #- ../geonetwork-ea-skin/templates/recordView.html:/usr/local/tomcat/webapps/geonetwork/catalog/views/default/templates/recordView.html
      - ../geonetwork-ea-skin/locales/en-custom.json:/usr/local/tomcat/webapps/geonetwork/catalog/locales/en-custom.json
      # schema overrides
            # dcat and non-spatial
      - ../iso19139.nonspatial/src/main/plugin/iso19139.nonspatial:/usr/local/tomcat/webapps/geonetwork/WEB-INF/data/config/schema_plugins/iso19139.nonspatial
      - ../iso19139.nonspatial/target/schema-iso19139.nonspatial-3.12-SNAPSHOT.jar:/usr/local/tomcat/webapps/geonetwork/WEB-INF/lib/schema-iso19139.nonspatial-3.12-SNAPSHOT.jar
      - ../iso19139.nonspatial/src/main/plugin/iso19139.nonspatial/layout/tpl-rdf-iso19139.xsl:/usr/local/tomcat/webapps/geonetwork/WEB-INF/data/config/schema_plugins/iso19139/layout/tpl-rdf.xsl
      - ../iso19139.nonspatial/web/src/main/webapp/xslt/services/dcat/rdf.xsl:/usr/local/tomcat/webapps/geonetwork/xslt/services/dcat/rdf.xsl
      #- ../nonspatialmetadata/schemas/iso19139/src/main/plugin/iso19139/present/csw/dcat-brief.xsl:/usr/local/tomcat/webapps/geonetwork/WEB-INF/config/data/config/schema_plugins/iso19139/present/csw/dcat-brief.xsl
      #GDPR
      - ../iso19139.gdpr/src/main/plugin/iso19139.gdpr:/usr/local/tomcat/webapps/geonetwork/WEB-INF/data/config/schema_plugins/iso19139.gdpr
      - ../iso19139.gdpr/target/schema-iso19139.gdpr-3.12-SNAPSHOT.jar:/usr/local/tomcat/webapps/geonetwork/WEB-INF/lib/schema-iso19139.gdpr-3.12-SNAPSHOT.jar
      #EAMP
      - ../iso19139.eamp/src/main/plugin/iso19139.eamp:/usr/local/tomcat/webapps/geonetwork/WEB-INF/data/config/schema_plugins/iso19139.eamp
      - ../iso19139.eamp/src/main/plugin/iso19139.eamp/src/main/config/translations/en-schema-iso19139.eamp.json:/usr/local/tomcat/webapps/geonetwork/catalog/locales/en-schema-iso19139.eamp.json
      - ../iso19139.eamp/target/schema-iso19139.eamp-3.12-SNAPSHOT.jar:/usr/local/tomcat/webapps/geonetwork/WEB-INF/lib/schema-iso19139.eamp-3.12-SNAPSHOT.jar
      #DCAT
      #- /home/ec2-user/schemas/dcat2-3.12.x/src/main/plugin/dcat2:/usr/local/tomcat/webapps/geonetwork/WEB-INF/data/config/schema_plugins/dcat2
      # gemini 2.3
      - ../iso19139.gemini23/src/main/plugin/iso19139.gemini23:/usr/local/tomcat/webapps/geonetwork/WEB-INF/data/config/schema_plugins/iso19139.gemini23
      - ../iso19139.gemini23/src/main/plugin/iso19139.gemini23/src/main/config/translations/en-schema-iso19139.gemini23.json:/usr/local/tomcat/webapps/geonetwork/catalog/locales/en-schema-iso19139.gemini23.json
      - ../iso19139.gemini23/target/schema-iso19139.gemini23-3.12-SNAPSHOT.jar:/usr/local/tomcat/webapps/geonetwork/WEB-INF/lib/schema-iso19139.gemini23-3.12-SNAPSHOT.jar
      - ./geonetwork/WEB-INF/data/config/schema_plugins/iso19139.gemini23/index-fields/index-subtemplate.xsl:/usr/local/tomcat/webapps/geonetwork/WEB-INF/data/config/schema_plugins/iso19139.gemini23/index-fields/index-subtemplate.xsl
      - ./geonetwork/WEB-INF/data/config/schema_plugins/iso19139.gemini23/layout/config-editor.xml:/usr/local/tomcat/webapps/geonetwork/WEB-INF/data/config/schema_plugins/iso19139.gemini23/layout/config-editor.xml
      # gemini 2.2
      - ../iso19139.gemini22_GN3/src/main/plugin/iso19139.gemini22:/usr/local/tomcat/webapps/geonetwork/WEB-INF/data/config/schema_plugins/iso19139.gemini22
      - ../iso19139.gemini22_GN3/src/main/plugin/iso19139.gemini22/src/main/config/translations/en-schema-iso19139.gemini22.json:/usr/local/tomcat/webapps/geonetwork/catalog/locales/en-schema-iso19139.gemini22.json
      - ../iso19139.gemini22_GN3/target/schema-iso19139.gemini22-3.7.jar:/usr/local/tomcat/webapps/geonetwork/WEB-INF/lib/schema-iso19139.gemini22-3.7.jar
      - ./geonetwork/xsl/conversion/import/xml_gemini22gemini23.xsl:/usr/local/tomcat/webapps/geonetwork/xsl/conversion/import/xml_gemini22gemini23.xsl
      - ../iso19139.gemini22_GN3-3.8.x/src/main/plugin/iso19139.gemini22/process/xml_gemini22gemini23-schemaupgrade.xsl:/usr/local/tomcat/webapps/geonetwork/WEB-INF/data/config/schema_plugins/iso19139/process/xml_gemini22gemini23-schemaupgrade.xsl
      # iso19139
      - ./geonetwork/WEB-INF/data/config/schema_plugins/iso19139/index-fields/index-subtemplate.xsl:/usr/local/tomcat/webapps/geonetwork/WEB-INF/data/config/schema_plugins/iso19139/index-fields/index-subtemplate.xsl
        # OS custom overrides
      
      # - ./geonetwork/catalog/config/batch-process-cfg.json:/usr/local/tomcat/webapps/geonetwork/catalog/config/batch-process-cfg.json
      # - ./geonetwork/WEB-INF/config/config-service-csw.xml:/usr/local/tomcat/webapps/geonetwork/WEB-INF/config/config-service-csw.xml
      # security overrides
      - ./geonetwork/WEB-INF/web.xml:/usr/local/tomcat/webapps/geonetwork/WEB-INF/web.xml
      - ./geonetwork/WEB-INF/config.properties.local:/usr/local/tomcat/webapps/geonetwork/WEB-INF/config.properties
      - ./geonetwork/META-INF/context.xml:/usr/local/tomcat/webapps/geonetwork/META-INF/context.xml
      - ./tomcat/server.xml:/usr/local/tomcat/conf/server.xml
      - ./tomcat/web.xml:/usr/local/tomcat/conf/web.xml
      # # osmp (WIP)
      # - ../iso19139.osmp/src/main/plugin/iso19139.osmp:/usr/local/tomcat/webapps/geonetwork/WEB-INF/data/config/schema_plugins/iso19139.osmp
      # - ../iso19139.osmp/target/schema-iso19139.osmp-3.10-SNAPSHOT.jar:/usr/local/tomcat/webapps/geonetwork/WEB-INF/lib/sschema-iso19139.osmp-3.10-SNAPSHOT.jar

  elasticsearch:
    image: elasticsearch:7.6.2
    container_name: elasticsearch
    logging:
      driver: "json-file"
    networks:
      - esnet
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
    environment:
      ES_JAVA_OPTS: "-Xms1G -Xmx1G"
      discovery.type: single-node
      xpack.security.enabled: "false"
      logger.level: WARN
    volumes:
      - esdata:/usr/share/elasticsearch/data

  # kibana:
  #   image: kibana:7.6.2
  #   container_name: kibana
  #   environment:
  #     SERVER_NAME: kibana
  #     SERVER_BASEPATH: /geonetwork/dashboards
  #     SERVER_REWRITEBASEPATH: 'false'
  #     KIBANA_INDEX: .dashboards
  #     XPACK_MONITORING_UI_CONTAINER_ELASTICSEARCH_ENABLED: 'true'
  #     ELASTICSEARCH_URL: http://elasticsearch:9200/
  #     #ELASTICSEARCH_USERNAME: elastic
  #     #ELASTICSEARCH_PASSWORD: changeme
  #   logging:
  #         driver: "json-file"
  #   networks:
  #     - esnet
  #   healthcheck:
  #       test: ["CMD-SHELL", "curl -f http://localhost:5601/login || exit 1"]
  #       interval: 1m
  #       timeout: 10s
  #       retries: 5

  

  postgres:
    image: postgis/postgis:12-master
    ports:
      - 5432:5432
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_DB_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgresql/audit.sql:/docker-entrypoint-initdb.d/1-audit.sql
    logging:
          driver: "json-file"
    networks:
      - esnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_DB_USERNAME} -d ${POSTGRES_DB_NAME}"]
      interval: 1m
      timeout: 10s
      retries: 3

  # nginx:
  #   image: nginx
  #   container_name: nginx
  #   volumes:
  #         - ./nginx/default.local:/etc/nginx/conf.d/default.conf
  #   ports:
  #     - "81:80"
  #   logging:
  #         driver: "json-file"
  #   networks:
  #     - esnet
  #   healthcheck:
  #     test: ["CMD-SHELL", "curl -f http://localhost:80/robots.txt || exit 1"]
  #     interval: 1m
  #     timeout: 10s
  #     retries: 5

# un-comment this only if it's needed
  # zeppelin:
  #   image: apache/zeppelin:0.9.0
  #   container_name: zeppelin
  #   volumes: 
  #     - ./shiro-geonetwork/geonetwork-integration/target/testshiro-1.0-SNAPSHOT-jar-with-dependencies.jar:/opt/zeppelin/lib/testshiro-1.0-SNAPSHOT-jar-with-dependencies.jar
  #     - ./zeppelin/zeppelin-notebook:/zeppelin/notebook
  #     - ./zeppelin/zeppelin-logs:/zeppelin/logs
  #     - ./shiro-geonetwork/lib/postgresql-42.2.12.jar:/opt/zeppelin/lib/postgresql-42.2.12.jar
  #     - ./shiro-geonetwork/conf/shiro.ini:/zeppelin/conf/shiro.ini
  #     - ./zeppelin/zeppelin-conf/interpreter-setting.json:/zeppelin/interpreter/jdbc/interpreter-setting.json
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     - "ZEPPELIN_INTERPRETER_OUTPUT_LIMIT=10490000"
  #     - "ZEPPELIN_INTERPRETER_INCLUDE=jdbc"  
  #     - "ZEPPELIN_INTERPRETER_GROUP_DEFAULT=jdbc"
  #     - "ZEPPELIN_PORT=8081"
  #     - "ZEPPELIN_ADDR=0.0.0.0"
  #     - "HOSTNAME=0.0.0.0"
  #   expose:
  #     - "8081"
  #   networks:
  #     - esnet
    #restart: unless-stopped


networks:
  esnet:
    driver: bridge