version: "3"

services:
  geohealthcheck:
    image: geopython/geohealthcheck:latest
    container_name: geohealthcheck
    restart: unless-stopped
    ports:
      - 8082:80

  ghc_runner:
    image: geopython/geohealthcheck:latest
    container_name: ghc_runner
    restart: unless-stopped
    entrypoint:
      - /run-runner.sh